application: infinitegraffitiwall
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.*\.(html))
  static_files: \1
  upload: (.*\.(html))
  
- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /js
  static_dir: js
  
- url: /
  static_files: index.html
  upload: index.html