application: infinitegraffitiwallclosedtest
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /audio/(.*\.(ogg|oga))
  mime_type: audio/ogg
  static_files: audio/\1
  upload: audio/(.*\.(ogg|oga))
  
- url: /audio/(.*\.mp3)
  mime_type: audio/mpeg
  static_files: audio/\1
  upload: audio/(.*\.mp3)

- url: /.*
  script: main.app
  
libraries:
- name: jinja2
  version: latest
  
builtins:
- remote_api: on
