from datetime import datetime
import unittest


def parse_datetime(s):
    # parse a datetime generated by datetime.now()
    try:
        return datetime.strptime(s, "%Y-%m-%d %H:%M:%S")
    except ValueError:
        return datetime.strptime(s, "%Y-%m-%d %H:%M:%S.%f")


class TestParseDateTime(unittest.TestCase):

    def testParseDateTime(self):
        d = datetime.now()
        self.assertEqual(parse_datetime(str(d)), d)
        d = datetime.now().replace(microsecond=0)
        self.assertEqual(parse_datetime(str(d)), d)
